CREATE SCHEMA application;
CREATE TABLE IF NOT EXISTS application.aircraft
(
    callsign CHARACTER VARYING(15) NOT NULL,
    model CHARACTER VARYING(50) NOT NULL,
    modeltype CHARACTER VARYING(50)NOT NULL,
    modelyear CHARACTER VARYING(4),
    CONSTRAINT aircraft_pkey PRIMARY KEY (callsign)
);

CREATE TABLE application.pilot(
	ID int generated by default as identity PRIMARY KEY NOT NULL,
	first_name varchar(50) NOT NULL,
	last_name varchar(50) NOT NULL
);


insert into application.pilot(first_name, last_name) values ('first_name_test', 'last_name_test');


insert into application.aircraft(callsign, model, modeltype, modelyear) values ('N5432', 'Cessna', 'Skyhawk 172', '2022');